# Generated by Django 4.2.7 on 2023-12-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_brandprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='about_services',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='brand_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='number_of_products',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='brand_profiles/'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='years_of_establishment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
