# Generated by Django 4.2.7 on 2023-12-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_influencerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='brand_images',
            field=models.ImageField(blank=True, null=True, upload_to='brand_related'),
        ),
    ]
